# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_travelplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='description',
            field=models.CharField(default='desc', max_length=255),
        ),
    ]
